# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 01:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=1000)),
                ('adate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DC_Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('A', 'Zeroth Review'), ('B', 'First DC'), ('C', 'Coursework Completion'), ('D', 'Comprehensive Viva'), ('E', 'RAC'), ('F', 'Second DC'), ('G', 'Thesis Submission'), ('H', 'Open Defence')], default='A', max_length=30)),
                ('remarks', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=500)),
                ('status', models.CharField(default='None', max_length=30)),
                ('marks', models.IntegerField(default=0)),
                ('sdate', models.DateField(blank=True, null=True)),
                ('cdate', models.DateField(blank=True, null=True)),
                ('Completed', models.BooleanField(default=False)),
                ('Started', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DCMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('pemail', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=30)),
                ('phno', models.CharField(max_length=11)),
                ('retitle', models.CharField(max_length=500)),
                ('typet', models.CharField(max_length=30)),
                ('regdate', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
                ('institution', models.CharField(max_length=500)),
                ('institution_ad', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('regno', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Su_Personal_Det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phno', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pemail', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=30)),
                ('aoi', models.CharField(max_length=500)),
                ('institution', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('mid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('dean', models.BooleanField(default=False)),
                ('external', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupMess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('regno', models.CharField(max_length=17)),
                ('mid', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='ThesisGuide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.Supervisor')),
            ],
        ),
        migrations.AddField(
            model_name='su_personal_det',
            name='supervisor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Research.Supervisor'),
        ),
        migrations.AddField(
            model_name='reports',
            name='scholar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.Scholar'),
        ),
        migrations.AddField(
            model_name='publications',
            name='scholars',
            field=models.ManyToManyField(to='Research.Scholar'),
        ),
        migrations.AddField(
            model_name='publications',
            name='supervisors',
            field=models.ManyToManyField(to='Research.Supervisor'),
        ),
        migrations.AddField(
            model_name='personal_det',
            name='scholar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Research.Scholar'),
        ),
        migrations.AddField(
            model_name='personal_det',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.Supervisor'),
        ),
        migrations.AddField(
            model_name='dcmember',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.Supervisor'),
        ),
        migrations.AddField(
            model_name='dc_meeting',
            name='guides',
            field=models.ManyToManyField(to='Research.ThesisGuide'),
        ),
        migrations.AddField(
            model_name='dc_meeting',
            name='scholar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.Scholar'),
        ),
        migrations.AddField(
            model_name='dc_meeting',
            name='supervisors',
            field=models.ManyToManyField(to='Research.DCMember'),
        ),
    ]
