# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-01 13:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(max_length=1000)),
                ('adate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DCMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('pemail', models.EmailField(max_length=254)),
                ('category', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=30)),
                ('phno', models.CharField(max_length=11)),
                ('retitle', models.CharField(max_length=500)),
                ('typet', models.CharField(max_length=30)),
                ('regdate', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=10)),
                ('dob', models.CharField(max_length=10)),
                ('institution', models.CharField(max_length=500)),
                ('institution_ad', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('name', models.CharField(max_length=40)),
                ('current', models.BooleanField(default=False)),
                ('result', models.CharField(max_length=5)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('date', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('regno', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Su_Personal_Det',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phno', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('pemail', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=10)),
                ('school', models.CharField(max_length=30)),
                ('aoi', models.CharField(max_length=500)),
                ('institution', models.CharField(max_length=500)),
                ('designation', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('mid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('dean', models.BooleanField(default=False)),
                ('external', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SupMess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('regno', models.CharField(max_length=17)),
                ('mid', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Research.Progress')),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('Research.progress',),
        ),
        migrations.CreateModel(
            name='DC',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Research.Progress')),
                ('date', models.DateField(null=True)),
                ('comments', models.CharField(max_length=500)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('Research.progress',),
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Research.Progress')),
                ('date', models.DateField(null=True)),
                ('marks', models.IntegerField()),
                ('comments', models.CharField(max_length=500)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('Research.progress',),
        ),
        migrations.CreateModel(
            name='Subjected',
            fields=[
                ('subject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Research.Subject')),
                ('datePassed', models.DateField(null=True)),
                ('marks', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.Coursework')),
            ],
            bases=('Research.subject',),
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Research.Progress')),
                ('date', models.DateField(null=True)),
                ('comments', models.CharField(max_length=30)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('Research.progress',),
        ),
        migrations.CreateModel(
            name='Zero',
            fields=[
                ('progress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Research.Progress')),
                ('presented', models.DateField(null=True)),
                ('fees', models.CharField(max_length=5)),
                ('datePaid', models.DateField(null=True)),
            ],
            options={
                'manager_inheritance_from_future': True,
            },
            bases=('Research.progress',),
        ),
        migrations.AddField(
            model_name='su_personal_det',
            name='supervisor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Research.Supervisor'),
        ),
        migrations.AddField(
            model_name='reports',
            name='scholar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.Scholar'),
        ),
        migrations.AddField(
            model_name='publications',
            name='scholars',
            field=models.ManyToManyField(to='Research.Scholar'),
        ),
        migrations.AddField(
            model_name='publications',
            name='supervisors',
            field=models.ManyToManyField(to='Research.Supervisor'),
        ),
        migrations.AddField(
            model_name='progress',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_research.progress_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='progress',
            name='scholar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.Scholar'),
        ),
        migrations.AddField(
            model_name='personal_det',
            name='scholar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Research.Scholar'),
        ),
        migrations.AddField(
            model_name='personal_det',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.Supervisor'),
        ),
        migrations.AddField(
            model_name='dcmembers',
            name='members',
            field=models.ManyToManyField(to='Research.Supervisor'),
        ),
        migrations.AddField(
            model_name='dcmembers',
            name='scholar',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Research.Scholar'),
        ),
    ]
