# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-18 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='scholar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Research.Scholar'),
        ),
    ]
