# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-17 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dc',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
