# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-06 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcmember',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='thesisguide',
            name='supervisor',
        ),
        migrations.RemoveField(
            model_name='dc_meeting',
            name='guides',
        ),
        migrations.AlterField(
            model_name='dc_meeting',
            name='supervisors',
            field=models.ManyToManyField(to='Research.Supervisor'),
        ),
        migrations.DeleteModel(
            name='DCMember',
        ),
        migrations.DeleteModel(
            name='ThesisGuide',
        ),
    ]
