# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-28 09:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0002_auto_20190318_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='latest',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
