# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0002_auto_20190317_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjected',
            name='marks',
            field=models.IntegerField(null=True),
        ),
    ]
