# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-16 04:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0003_auto_20190314_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('deanText', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deanText', to='Research.Supervisor')),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.Scholar')),
                ('supervisorText', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisorText', to='Research.Supervisor')),
            ],
        ),
        migrations.RemoveField(
            model_name='reports',
            name='scholar',
        ),
        migrations.AddField(
            model_name='dc',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dc',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Reports',
        ),
        migrations.AddField(
            model_name='comments',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Research.Message'),
        ),
    ]
