# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0004_auto_20190328_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='doc',
            field=models.FileField(null=True, upload_to='thesis/'),
        ),
    ]
