# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-30 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0005_thesis_doc'),
    ]

    operations = [
        migrations.AddField(
            model_name='others',
            name='doc',
            field=models.FileField(null=True, upload_to='synopsis/'),
        ),
    ]
