# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-03-30 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Research', '0006_others_doc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dc',
            old_name='time',
            new_name='start',
        ),
        migrations.AddField(
            model_name='dc',
            name='end',
            field=models.TimeField(null=True),
        ),
    ]
